# Generated by Django 4.2 on 2023-04-18 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='artist_since',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
