# Generated by Django 4.2 on 2023-05-02 16:49

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='main_photo',
            field=models.ImageField(default='no_image', upload_to=users.models.user_directory_path),
        ),
    ]
