# Generated by Django 4.2 on 2023-05-25 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_blogpost_delete_sliderimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-post_date']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
